SQL CODE FOR ORDER_SUMMARY:

WITH ORDER_SUMMARY AS
(
SELECT 
	ORDER_ID,
	CUSTOMER_ID,
	PRODUCT_NAME,
	CATEGORY,
	QUANTITY,
	PRICE,
	QUANTITY*PRICE AS TOTAL_AMOUNT
FROM ORDERS ORD
LEFT JOIN PRODUCTS PRO
ON 1=1
AND ORD.PRODUCT_ID=PRO.PRODUCT_ID
)
SELECT * FROM ORDER_SUMMARY

# Database connection parameters
DB_HOST = 'localhost'
DB_NAME = 'postgres'
DB_USER = 'postgres'
DB_PASSWORD = 'Appaji@1970'
DB_PORT = '5432'
